CREATE ROLE tino_migrator LOGIN PASSWORD 'tino_migrator' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE tino_app LOGIN PASSWORD 'tino_app' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
GRANT CONNECT ON DATABASE tino TO tino_migrator, tino_app;
GRANT CREATE, USAGE ON SCHEMA public TO tino_migrator;
GRANT USAGE ON SCHEMA public TO tino_app;
