plugins { id("tino.java-conventions") }

dependencies {
    compileOnly(libs.spring.modulith.starter.core)
    api(platform(libs.spring.boot.dependencies))
    implementation(project(":shared:kernel"))
    implementation(project(":shared:infrastructure"))
    implementation(project(":modules:business"))
    implementation(project(":modules:identity"))
    implementation(project(":modules:customer"))
    implementation(project(":modules:credit"))
    implementation(project(":modules:payment"))
    implementation(project(":modules:messaging"))
    implementation(libs.spring.context)
    implementation(libs.spring.tx)
    implementation(libs.spring.jdbc)
    implementation(libs.spring.boot.starter.web)
    implementation(libs.spring.boot.starter.security)
    implementation(libs.jooq)
    implementation("nl.martijndwars:web-push:5.1.2")
    implementation("org.apache.httpcomponents:httpasyncclient:4.1.5")
    implementation("org.asynchttpclient:async-http-client:2.12.4")
    implementation("org.bitbucket.b_c:jose4j:0.7.9")
    implementation("org.bouncycastle:bcprov-jdk15on:1.70")
    testImplementation(libs.spring.boot.starter.test)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}
