package com.tino.backend.shared.kernel;

import java.security.SecureRandom;
import java.time.Instant;
import java.util.UUID;

/**
 * Application-side UUID version 7 generator.
 *
 * <p>The first 48 bits contain Unix epoch milliseconds. A per-millisecond
 * sequence in the UUID's {@code rand_a} field keeps identifiers generated by
 * this instance ordered when the clock has not advanced, while the remaining
 * random bits preserve collision resistance.</p>
 */
public final class UuidV7Generator implements UuidGenerator {
    private static final long TIMESTAMP_MASK = 0x0000FFFFFFFFFFFFL;
    private static final int SEQUENCE_MASK = 0x0FFF;
    private static final long VERSION_BITS = 0x7000L;
    private static final long VARIANT_BITS = 0x8000000000000000L;
    private static final long RANDOM_LOW_MASK = 0x3FFFFFFFFFFFFFFFL;

    private final SecureRandom random;
    private long lastTimestamp = -1L;
    private int sequence;

    public UuidV7Generator() {
        random = new SecureRandom();
        sequence = random.nextInt(SEQUENCE_MASK + 1);
    }

    @Override
    public synchronized UUID next() {
        long timestamp = Instant.now().toEpochMilli();
        if (timestamp <= lastTimestamp) {
            timestamp = lastTimestamp;
            sequence++;
            if ((sequence & ~SEQUENCE_MASK) != 0) {
                timestamp = lastTimestamp + 1L;
                sequence = random.nextInt(SEQUENCE_MASK + 1);
            }
        } else {
            sequence = random.nextInt(SEQUENCE_MASK + 1);
        }
        lastTimestamp = timestamp;

        long mostSignificantBits = (timestamp & TIMESTAMP_MASK) << 16;
        mostSignificantBits |= VERSION_BITS | (sequence & SEQUENCE_MASK);
        long leastSignificantBits = VARIANT_BITS | (random.nextLong() & RANDOM_LOW_MASK);
        return new UUID(mostSignificantBits, leastSignificantBits);
    }
}
